### ISSUE TITLE
Pivots are visible through doors

### ISSUE THREAD

**Issue by danielgordon10** [allenai/ai2thor#27]
All of the pivot locations should be checked (probably by hand) to make sure this never happens. Sometimes it seems like the coordinate systems are flipped in weird ways (x and y are reversed for example) and it makes the pivot locations outside of the object entirely. One example is Floorplan13 the 3 cabinets on the wall starting with Cabinet|-03.04|+00.47|+05.03

**Comment by roozbehm** [comment]
These bugs have been fixed in version 0.0.25.

**Comment by lichengunc** [comment]
Seems not fixed yet. Could you check again?
For example, FloorPlan6's Bowl|+00.41|+01.65|-01.73 is inside the cabinet but visible and pickable to agent (before opening the cabinet).

**Comment by roozbehm** [comment]
We will update you about this soon.

**Comment by ekolve** [comment]
This is fixed with the latest release (0.0.31), please confirm when you have a chance.  Each of the drawers, cabinets were check programmatically and fixed in all scenes.

**Comment by danielgordon10** [comment]
There are still some issues, though overall it seems MUCH better. Here are two cases I have found.
1. Drawers where the object is so tall it pokes out of the top. Possible solutions are treating drawers differently from cabinets in randomInitialize or resizing the objects (but then they may end up really small), or putting the objects in a pivot on their side.
![state_00259](https://user-images.githubusercontent.com/7245472/41481078-83373936-7085-11e8-9b1e-1820eabab298.jpg)
![state_00258](https://user-images.githubusercontent.com/7245472/41481082-86b0802c-7085-11e8-92c2-c94e77d48db1.jpg)

2. Random few pixels visible through doors. Not quite sure what causes this. May be a corner case in Unity rendering. We can look for the number of pixels area an object has, and color it in as the closest nearby color if it is under a certain threshold, but that may take a fair amount of computational resources. By fair amount I mean it may slow it down by 2-10 FPS which could be a big deal.

![state_00266](https://user-images.githubusercontent.com/7245472/41481108-9e231abc-7085-11e8-9f78-3563f430d30b.jpg)

Both of these were found in FloorPlan 18 for reference.

**Comment by danielgordon10** [comment]
Here's an instance of it still visible through the door. Floorplan15.
![state_00251](https://user-images.githubusercontent.com/7245472/41493007-21058ae6-70b8-11e8-9a1d-ce5109003ef9.jpg)

**Comment by ekolve** [comment]
Fixed with latest version (1.0.1)
